env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
globals:
  AFRAME: readonly
  THREE: readonly
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
