site_name: Superquest
pages:
    - Home: index.md
    - Extras Collection: aframe-extra-collection.md
    - Extra Shaders: aframe-extra-shaders.md
    - Extra Utils: aframe-extra-utils.md
    - Google Poly Loader: aframe-google-poly.md
    - Locomote Controls: aframe-locomote-controls.md
    - Lite Physics: aframe-physics-lite.md
    - Oculus Quest Hands: aframe-oculus-hands.md
    - Assets: assets.md

theme: readthedocs